---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-h-share-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: media
    name: media-nfs-h-share-pvc
  storageClassName: nfs
  nfs:
    server: 10.0.0.243
    path: "/export/hwe"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-h-share-pvc
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi

