---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-crds
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-system-helm-repositories
  interval: 10m0s
  path: ./cluster/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-gpg
  # postBuild:
  #   substitute: {}
  #   substituteFrom:
  #   - kind: ConfigMap
  #     name: cluster-settings
  #   - kind: Secret
  #     name: cluster-secrets