---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: plexinc/pms-docker
      tag: latest

    env:
      ADVERTISE_IP: "http://10.0.0.201:32400"

    service:
      port:
        port: 32400
      additionalServices:
        - enabled: true
        #   nameSuffix: dnla-tcp
          type: NodePort
          port:
            port: 32469
          #     name: dnla-tcp
            protocol: TCP
    #     targetPort: 32469
    #   externalTrafficPolicy: Local
    # - enabled: true
    #   nameSuffix: dnla-udp
    #   type: NodePort
    #   port:
    #     port: 1900
    #     name: dnla-udp
    #     protocol: UDP
    #     targetPort: 1900
    #   externalTrafficPolicy: Local

    resources:
      limits:
        # gpu.intel.com/i915: 1
        # nvidia.com/gpu: 1
        memory: 5009Mi
      requests:
        cpu: 763m
        memory: 5009Mi
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-pvc
