---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: plexinc/pms-docker
      tag: latest
    env:
      ADVERTISE_IP: "http://10.0.0.201:32400" 
    service:
      enabled: true
      type: NodePort
      ports:
        app:
          port: 32400
      protocol: TCP
    # nodeSelector:
    #   app: "nvidia-gpu-plugin"
    resources:
      limits:
        # gpu.intel.com/i915: 1
        # nvidia.com/gpu: 1
        memory: 5009Mi
      requests:
        cpu: 763m
        memory: 5009Mi
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-pvc
    additionalVolumes:
    - name: nfs-media-pvc
      persistentVolumeClaim:
        claimName: nfs-media-pvc
    additionalVolumeMounts:
    - name: nfs-media-pvc
      mountPath: /data
      readOnly: false